gauges_id:
google_analytics_id:

collections:
  templates:
    name: Jekyll Themes
  snippets:
    name: Jekyll Snippets
    output: true
  services:
    name: Services for Static Sites
  tutorials:
    name: Jekyll Tutorials
  guide:
    name: Get Started Guide
    output: true

defaults:
  -
    scope:
      path: ""
      type: snippets
    values:
      layout: snippet
      permalink: :collection/:title/
  -
    scope:
      path: ""
      type: guide
    values:
      layout: docs
      permalink: :collection/:title/
