google_analytics_id: UA-37472773-14

collections:
  templates:
    name: Jekyll Themes
  snippets:
    name: Jekyll Snippets
    output: true
    permalink: /:collection/:title/
  services:
    name: Services for Static Sites
  tutorials:
    name: Jekyll Tutorials
  guide:
    name: Get Started Guide
    output: true
    permalink: /:collection/:title/

defaults:
  -
    scope:
      path: ""
      type: snippets
    values:
      layout: snippet
  -
    scope:
      path: ""
      type: guide
    values:
      layout: docs
