google_analytics_id: UA-37472773-14
collections:
  templates:
    name: Jekyll Themes
  services:
    name: Services for Static Sites
  tutorials:
    name: Jekyll Tutorials
    output: true
    permalink: "/:collection/:title/"
  guide:
    name: Get Started Guide
    output: true
    permalink: "/:collection/:title/"
defaults:
  - scope:
      path: ""
      type: tutorials
    values:
      layout: snippet
  - scope:
      path: ""
      type: guide
    values:
      layout: docs
