collections:
  themes:
  snippets:
    output: true
  static_site_services:
  tutorials:
main_links:
  - title: Themes
    link: /
  - title: Tutorials
    link: /tutorials/
  - title: Snippets
    link: /snippets/
  - title: Services for Static Sites
    link: /services-for-static-sites/
